name: upload-storybook
on: [push, pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: rm -rf .out
        shell: bash
      - run: yarn build:story
      - uses: actions/upload-artifact@v1
        with:
          name: storybook
          path: artifact
